repositories:
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: external-secrets
    url: https://charts.external-secrets.io

environments:
  PROD:
  DEV:



releases:
  - name: my-release
    chart: ./blogchart
    version: "1.0.0"
    values:
      - {{ .Environment.Name }}/blogchart-values.yaml
      
  - name: ingress-nginx
    chart: ingress-nginx/ingress-nginx
    version: 4.12.0  # Specify the version you want to use
    namespace: ingress-nginx 

  - name: external-secrets
    chart: external-secrets/external-secrets
    version: 0.13.0  # Match the version of ESO you referenced
    namespace: external-secrets 