apiVersion: v1
kind: Service
metadata:
  name: your-app-service
  namespace: default
spec:
  selector:
    app: your-app
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer  # or ClusterIP, depending on your use case
