apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.deployment.name }}
  namespace: {{ .Values.frontend.deployment.namespace }}
spec:
  replicas: {{ .Values.frontend.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.frontend.deployment.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.frontend.deployment.app }}
    spec:
      containers:
        - name: {{ .Values.frontend.container.name }}
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.frontendtag }}"
          ports:
            - containerPort: {{ .Values.frontend.container.port }}
      imagePullSecrets:
        - name: {{ .Values.frontend.image.imagePullSecrets }}
