apiVersion: apps/v1
kind: Deployment
metadata:
  name: your-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: your-app
  template:
    metadata:
      labels:
        app: your-app
    spec:
      containers:
        - name: your-app
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.frontendtag }}"  # Replace with your private image
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: registry-secret  # Reference to the secret created earlier
