apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.service.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.frontend.deployment.app }}
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP  # or ClusterIP, depending on your use case
