apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: default
spec:
  selector:
    app: your-app
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP  # or ClusterIP, depending on your use case
