name: Generate and Push new YAML

on:
  push:
    branches:
      - main  # Adjust this to the branch you want the pipeline to run on




jobs:
  list-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: List all files in the repository
        run: |
          echo "Listing all files in the repository:"
          ls -R

      - name: Clone the target repository
        run: |
          git clone https://github.com/yuvalmaor/gitops-blog.git target-repo
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      - name: List all files in the repository
        run: |
          echo "Listing all files in the repository:"
          ls -R

      - name: List all files in the repository
        run: |
          echo "Listing all files in the repository:"
          ls -la ./target-repo

      - name: Install Helm and Helmfile
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh
      - name : ls pwd
        run: |
          ls
          pwd
      # Step 4: Generate new generated.yaml using helmfile template
      - name: Generate new generated.yaml
        run: |
          echo "Running helmfile template to generate generated.yaml"
          helmfile template | tee generated.yaml