name: Generate and Push new YAML

on:
  push:
    branches:
      - main  # Adjust this to the branch you want the pipeline to run on

permissions:
  contents: write
  pull-requests: write


jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      
      # Step 1: Checkout the 'gitops-blog' repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: yuvalmaor/gitops-blog  # Make sure this targets the correct repository
          token: ${{ secrets.PAT_TOKEN }}  # Use the PAT token to authenticate
      - name : ls pwd
        run: |
          ls
          pwd
      # Step 2: Delete generated.yaml if it exists
      - name: Delete generated.yaml if it exists
        run: |
          if [ -f generated.yaml ]; then
            echo "Deleting generated.yaml"
            rm generated.yaml
          else
            echo "generated.yaml does not exist, skipping deletion"
          fi

      # Step 3: Install Helm and Helmfile
      - name: Install Helm and Helmfile
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh
      - name : ls pwd
        run: |
          ls
          pwd
      # Step 4: Generate new generated.yaml using helmfile template
      - name: Generate new generated.yaml
        run: |
          echo "Running helmfile template to generate generated.yaml"
          helmfile template | tee generated.yaml

      # Step 5: Commit and push the changes back to the 'gitops-blog' repository using PAT
      - name: Commit and push changes 
        env:
          TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/yuvalmaor/gitops-blog.git
          git add generated.yaml
          git commit -m "Regenerate generated.yaml"
          git push