name: Generate and Push new YAML

on:
  push:
    branches:
      - main  # Adjust this to the branch you want the pipeline to run on




jobs:
  list-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: List all files in the repository
        run: |
          echo "Listing all files in the repository:"
          ls -R