name: Generate and Push new YAML

on:
  push:
    branches:
      - main  # Adjust this to the branch you want the pipeline to run on




jobs:
  list-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: List all files in the repository
        run: |
          echo "Listing all files in the repository:"
          ls -R

      - name: Clone the target repository
        run: |
          git clone https://github.com/yuvalmaor/gitops-blog.git target-repo
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      - name: List all files in the repository
        run: |
          echo "Listing all files in the repository:"
          ls -R

      - name: List all files in the repository
        run: |
          echo "Listing all files in the repository:"
          ls -la ./target-repo

      - name: Install Helm and Helmfile
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh
      - name : ls pwd
        run: |
          ls
          pwd
      - name: Download Helmfile
        run: |
          curl -L -o helmfile.tar.gz https://github.com/helmfile/helmfile/releases/download/v0.170.1/helmfile_0.170.1_linux_amd64.tar.gz

      - name: Extract Helmfile
        run: |
          mkdir helmfile-bin
          tar -xzf helmfile.tar.gz -C helmfile-bin

      - name: Install Helmfile
        run: |
          sudo mv helmfile-bin/helmfile /usr/local/bin/
          chmod +x /usr/local/bin/helmfile

      - name: Verify Helmfile Installation
        run: |
          helmfile version
      # Step 4: Generate new generated.yaml using helmfile template
      - name: Generate new generated.yaml
        run: |
          echo "Running helmfile template to generate generated.yaml"
          helmfile template | tee generated.yaml
      - name: print yaml
        run: |
          helmfile template 
      - name: List all files in the repository
        run: |
          echo "Listing all files in the repository:"
          ls -R

      - name: Replace generated.yaml in target repository
        run: |
          echo "Replacing generated.yaml in target repository"
          cp ./generated.yaml ./target-repo/generated.yaml
      - name: cat
        run: |
          cat generated.yaml
          cat ./target-repo/generated.yaml
          
      # Step 7: Commit and push the changes to the target repository
      - name: Commit and push changes to target repository
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          cd target-repo
          ls -la 

          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add generated.yaml
          git commit -m "Replace generated.yaml with the new version"
          git push