name: Generate and Push new YAML

on:
  push:
    branches:
      - main  # Adjust this to the branch you want the pipeline to run on

jobs:
  generate-yaml:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the 'gitops-blog' repository
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        repository: yuvalmaor/gitops-blog  # Make sure this targets the correct repository

    # Step 2: Delete generated.yaml if it exists
    - name: Delete generated.yaml if it exists
      run: |
        if [ -f generated.yaml ]; then
          echo "Deleting generated.yaml"
          rm generated.yaml
        else
          echo "generated.yaml does not exist, skipping deletion"
        fi

    # Step 3: Install Helm and Helmfile
    - name: Install Helm and Helmfile
      run: |
        curl -fsSL https://get.helm.sh/helm-v3.11.1-linux-amd64.tar.gz | tar -xzv
        sudo mv linux-amd64/helm /usr/local/bin/helm
        curl -fsSL https://github.com/roboll/helmfile/releases/download/v0.150.0/helmfile_linux_amd64 > helmfile
        chmod +x helmfile
        sudo mv helmfile /usr/local/bin/

    # Step 4: Generate new generated.yaml using helmfile template
    - name: Generate new generated.yaml
      run: |
        echo "Running helmfile template to generate generated.yaml"
        helmfile template | tee generated.yaml

    # Step 5: Commit and push the changes back to the 'gitops-blog' repository
    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add generated.yaml
        git commit -m "Regenerate generated.yaml"
        git push
